import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import Providers from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <div className="w-screen h-screen">
          <Providers>{children}</Providers>
=======
      <body
        className={inter.className}
      >
        <div className='w-screen h-screen bg-white sm:bg-purple-lighter'>
          <Toaster />
          <ReduxProvider>
            {children}
          </ReduxProvider>
>>>>>>> 33e9815e366f35fb7add03644558546d1e8034c2
        </div>
      </body>
    </html>
  );
}
