import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import Image from "next/image";

import ReduxProvider from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div className='w-screen h-screen '>
          <div className='overflow-y-auto h-full flex flex-col bg-white sm:bg-purple-lighter'>
            <div className="w-full hidden sm:flex justify-center items-center bg-white p-2  shadow h-[64px] border-b-[1px] border-purple-main ">
              <Image alt='profitAll Logo' src='/images/logo-purple.svg' width={100} height={18} priority/>
            </div>
            <div className="h-full w-full flex flex-col justify-center items-center  sm:bg-purple-lighter ">
              <div className="logo-position w-full p-4 flex sm:hidden items-center justify-center">
                <Image alt='profitAll Logo' src='/images/logo-purple.svg' width={100} height={18} priority />
              </div>
              <ReduxProvider>
                {children}
              </ReduxProvider>
            </div> 
          </div>
        </div>
      </body>
    </html>
  );
}
